//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dayz_online
    {
        public long dayz_server_id { get; set; }
        public byte slot { get; set; }
        public string name { get; set; }
        public string ip_address { get; set; }
        public string guid { get; set; }
        public byte lobby { get; set; }
        public int ping { get; set; }
        public sbyte verified { get; set; }
        public System.DateTime last_updated { get; set; }
    }
}
