//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNet.IoC.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dayz_server
    {
        public long id { get; set; }
        public long server_id { get; set; }
        public string short_name { get; set; }
        public string name { get; set; }
        public long db_type { get; set; }
        public string db_host { get; set; }
        public int db_port { get; set; }
        public string db_dbname { get; set; }
        public string db_user { get; set; }
        public string db_password { get; set; }
        public string rcon_host { get; set; }
        public int rcon_port { get; set; }
        public string rcon_pwd { get; set; }
    }
}
